version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
      
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database_1
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
